services:
  n8n:
    build: .
    ports: ["5678:5678"]
    restart: unless-stopped
    environment:
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - NODE_FUNCTION_ALLOW_BUILTIN=child_process,fs,path,os
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=${N8N_PROTOCOL:-http}://${N8N_WEBHOOK_URL:-localhost:5678}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/New_York}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

volumes:
  n8n_data: